// schemas/lesson.js
export default {
  name: 'lesson',
  title: 'Lesson',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Lesson Title',
      type: 'string',
      description: 'The title of this specific lesson.',
      // validation: Rule => Rule.required().min(3).max(80),
    },
    {
      name: 'slug',
      title: 'Lesson Slug',
      type: 'slug',
      options: {
        source: 'title',
        // maxLength: 96,
      },
      // validation: Rule => Rule.required(),
      description: 'A unique identifier for the lesson URL.'
    },
    {
      name: 'course',
      title: 'Parent Course',
      type: 'reference',
      to: [{ type: 'course' }],
      // validation: Rule => Rule.required(),
      description: 'The course this lesson belongs to.'
    },
    {
      name: 'order',
      title: 'Order in Course',
      type: 'number',
      description: 'The numerical order of this lesson within its parent course (e.g., 1, 2, 3...).',
      // validation: Rule => Rule.required().integer().min(1),
    },
    {
      name: 'mainMedia',
      title: 'Main Lesson Media',
      type: 'image',
      options: {
        hotspot: true,
      },
      description: 'Main image or visual representation for this lesson, often sourced automatically (e.g., from Pixabay).',
    },
    {
      name: 'content',
      title: 'Lesson Content',
      type: 'array',
      of: [
        {
          type: 'block', // Permite texto rico (parágrafos, negrito, itálico, listas)
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H1', value: 'h1' },
            { title: 'H2', value: 'h2' },
            { title: 'H3', value: 'h3' },
            { title: 'H4', value: 'h4' },
            { title: 'Quote', value: 'blockquote' }
          ],
          lists: [{ title: 'Bullet', value: 'bullet' }, { title: 'Numbered', value: 'number' }],
          marks: {
            decorators: [{ title: 'Strong', value: 'strong' }, { title: 'Emphasis', value: 'em' }],
            annotations: [
              { name: 'link', type: 'object', title: 'URL', fields: [{ name: 'href', type: 'url', title: 'URL' }] },
            ],
          },
        },
        {
          type: 'image', // Permite adicionar imagens **dentro** do conteúdo (Portable Text)
          options: { hotspot: true },
        },
        {
          name: 'codeBlock', // Permite blocos de código formatados, essencial para cursos de programação
          title: 'Code Block',
          type: 'code',
          options: {
            theme: 'github',
            // languageAlternatives: [ ... ] // Exemplo: { title: 'JavaScript', value: 'javascript' }
          }
        }
      ],
      description: 'The main content of the lesson, typically generated by ChatGPT.',
      // validation: Rule => Rule.required(),
    },
    {
      name: 'estimatedReadingTime',
      title: 'Estimated Reading Time (minutes)',
      type: 'number',
      description: 'Estimated time for the member to complete this lesson.',
      initialValue: 5,
    },
    {
      // --- CAMPO STATUS ATUALIZADO PARA CONSISTÊNCIA COM 'COURSE' ---
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Published', value: 'published' },
          { title: 'Draft', value: 'draft' },
          { title: 'Pending', value: 'pending' },
          { title: 'Private', value: 'private' },
          { title: 'Archived', value: 'archived' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft', // Mantendo 'draft' como valor inicial padrão para lições
      description: 'Current publication status of the lesson, consistent with Course status.'
    },
  ],
  preview: {
    select: {
      title: 'title',
      courseTitle: 'course.title',
      order: 'order',
      status: 'status',
      media: 'mainMedia',
    },
    prepare(selection) {
      const { title, courseTitle, order, status, media } = selection;
      return {
        title: `${order ? `${order}. ` : ''}${title || 'New Lesson (Title Pending)'}`,
        subtitle: `${courseTitle ? `Course: ${courseTitle}` : 'No Course'} (${status})`,
        media: media,
      };
    },
  },
};